"""feat: additional blob table

Revision ID: 27acc10d3603
Revises: c874c1f3a9c1
Create Date: 2026-02-18 09:08:34.435872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27acc10d3603'
down_revision: Union[str, Sequence[str], None] = 'c874c1f3a9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos_blob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provedor', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('provedor_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('extensao', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('usuarios', sa.Column('criado_em', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'criado_em')
    op.drop_table('arquivos_blob')
    # ### end Alembic commands ###
