"""first migration

Revision ID: 62435dd31af0
Revises: 
Create Date: 2026-02-14 18:54:31.951454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62435dd31af0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('imagem_perfil', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('telefone', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('excluido', sa.Boolean(), nullable=False),
    sa.Column('senha', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
