"""fix: change columns types

Revision ID: 97abdde2da83
Revises: eb2b6a72343f
Create Date: 2026-02-18 10:05:18.736820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97abdde2da83'
down_revision: Union[str, Sequence[str], None] = 'eb2b6a72343f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('arquivos_blob', 'criado_em',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('avatar_blob_id', sa.Integer(), nullable=True))
    op.alter_column('usuarios', 'criado_em',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_foreign_key(None, 'usuarios', 'arquivos_blob', ['avatar_blob_id'], ['id'])
    op.drop_column('usuarios', 'avatar_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('avatar_url', mysql.VARCHAR(length=300), nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.alter_column('usuarios', 'criado_em',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    op.drop_column('usuarios', 'avatar_blob_id')
    op.alter_column('arquivos_blob', 'criado_em',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    # ### end Alembic commands ###
