"""fix(Users): correction image column in usertables

Revision ID: c874c1f3a9c1
Revises: 3583da009405
Create Date: 2026-02-14 19:15:05.485724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c874c1f3a9c1'
down_revision: Union[str, Sequence[str], None] = '3583da009405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True))
    op.drop_column('usuarios', 'imagem_perfil')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('imagem_perfil', mysql.VARCHAR(length=300), nullable=True))
    op.drop_column('usuarios', 'avatar_url')
    # ### end Alembic commands ###
